# Generated by Django 5.1.3 on 2025-03-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_managers_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(default='Test', max_length=255),
            preserve_default=False,
        ),
    ]
