# Generated by Django 5.1.3 on 2025-03-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Servi', 'Servi'), ('Annulé', 'Annulé'), ('Payé', 'Payé')], default='En attente', max_length=50),
        ),
    ]
